import type { AppData } from "./types";

const uid = (p: string, n: number) => `${p}-${n}`;

export const seedData: AppData = {
  goals: {
    totalRevenueGoal: 99500,
    cashGoal: 51500,
    inKindGoal: 48000,
    totalExpenses: 69249,
    boardGivingGoal: 25000,
    channels: [
      { name: "Individual Giving", goal: 12000, raised: 6450 },
      { name: "Major Gifts", goal: 15000, raised: 7500 },
      { name: "Grants", goal: 35000, raised: 20000 },
      { name: "Corporate Sponsorships", goal: 20000, raised: 11000 },
      { name: "Events", goal: 12000, raised: 4500 },
      { name: "Program Fees", goal: 5500, raised: 2100 },
    ],
  },
  grants: [
    {
      id: uid("grant", 1),
      funderName: "Chicago Community Trust",
      fundingType: "Foundation",
      priorityArea: "Youth Development",
      geographicFocus: "Cook County, IL",
      programFit: "Pathways Academic & Leadership Academy",
      amountRequested: 25000,
      likelihood: "High",
      deadline: "2026-03-15",
      status: "Submitted",
      loiDueDate: "2026-01-15",
      applicationDueDate: "2026-03-15",
      reportDueDate: "",
      contactName: "Denise Walker",
      contactEmail: "dwalker@cct.org",
      relationshipNotes: "Program officer attended last year's showcase.",
      nextStep: "Await decision; send Q1 program photos.",
      assignedOwner: "Executive Director",
      documentsNeeded: "990, board list, budget",
      submittedDate: "2026-03-10",
      decisionDate: "",
      awardAmount: 0,
      declinedReason: "",
      renewalOpportunity: true,
      notes: "Strong alignment with academic priority area.",
    },
    {
      id: uid("grant", 2),
      funderName: "Polk Bros. Foundation",
      fundingType: "Foundation",
      priorityArea: "Education & Out-of-School Time",
      geographicFocus: "Chicago",
      programFit: "Great Lakes Academy Summer Enrichment Program",
      amountRequested: 20000,
      likelihood: "Medium",
      deadline: "2026-05-01",
      status: "LOI Submitted",
      loiDueDate: "2026-02-01",
      applicationDueDate: "2026-05-01",
      reportDueDate: "",
      contactName: "Marcus Lee",
      contactEmail: "mlee@polkbros.org",
      relationshipNotes: "Introduced by board member.",
      nextStep: "Follow up on invitation to full proposal.",
      assignedOwner: "Grants Manager",
      documentsNeeded: "LOI, logic model",
      submittedDate: "",
      decisionDate: "",
      awardAmount: 0,
      declinedReason: "",
      renewalOpportunity: true,
      notes: "",
    },
    {
      id: uid("grant", 3),
      funderName: "Nike Community Impact Fund",
      fundingType: "Corporate Foundation",
      priorityArea: "Sports-Based Youth Development",
      geographicFocus: "Chicago Metro",
      programFit: "The Kinetic Lab",
      amountRequested: 15000,
      likelihood: "High",
      deadline: "2026-04-20",
      status: "Awarded",
      loiDueDate: "",
      applicationDueDate: "2026-02-20",
      reportDueDate: "2026-12-15",
      contactName: "Tasha Bryant",
      contactEmail: "tasha.bryant@nike.com",
      relationshipNotes: "Multi-year supporter.",
      nextStep: "Submit interim report in December.",
      assignedOwner: "Grants Manager",
      documentsNeeded: "Final report template",
      submittedDate: "2026-02-18",
      decisionDate: "2026-04-01",
      awardAmount: 15000,
      declinedReason: "",
      renewalOpportunity: true,
      notes: "Funds STEM + movement curriculum.",
    },
    {
      id: uid("grant", 4),
      funderName: "Crown Family Philanthropies",
      fundingType: "Family Foundation",
      priorityArea: "Leadership Development",
      geographicFocus: "Illinois",
      programFit: "General Operating Support",
      amountRequested: 10000,
      likelihood: "Medium",
      deadline: "2026-06-30",
      status: "Qualified",
      loiDueDate: "2026-04-15",
      applicationDueDate: "2026-06-30",
      reportDueDate: "",
      contactName: "Robert Crown",
      contactEmail: "info@crownmemorial.org",
      relationshipNotes: "Cold prospect; researching alignment.",
      nextStep: "Request intro meeting.",
      assignedOwner: "Executive Director",
      documentsNeeded: "Case for support",
      submittedDate: "",
      decisionDate: "",
      awardAmount: 0,
      declinedReason: "",
      renewalOpportunity: false,
      notes: "",
    },
    {
      id: uid("grant", 5),
      funderName: "Allstate Foundation",
      fundingType: "Corporate Foundation",
      priorityArea: "Career Exposure",
      geographicFocus: "Chicagoland",
      programFit: "Pathways Academic & Leadership Academy",
      amountRequested: 12000,
      likelihood: "Low",
      deadline: "2026-02-28",
      status: "Declined",
      loiDueDate: "",
      applicationDueDate: "2026-01-28",
      reportDueDate: "",
      contactName: "Jenny Park",
      contactEmail: "jpark@allstate.com",
      relationshipNotes: "",
      nextStep: "Re-apply next cycle with stronger outcomes data.",
      assignedOwner: "Grants Manager",
      documentsNeeded: "",
      submittedDate: "2026-01-25",
      decisionDate: "2026-02-28",
      awardAmount: 0,
      declinedReason: "Highly competitive cycle; encouraged to reapply.",
      renewalOpportunity: true,
      notes: "",
    },
    {
      id: uid("grant", 6),
      funderName: "Illinois DCEO Youth Grant",
      fundingType: "Government",
      priorityArea: "STEM Education",
      geographicFocus: "Illinois",
      programFit: "The Kinetic Lab",
      amountRequested: 18000,
      likelihood: "Medium",
      deadline: "2026-06-15",
      status: "Reporting Due",
      loiDueDate: "",
      applicationDueDate: "2025-09-15",
      reportDueDate: "2026-06-30",
      contactName: "State Program Office",
      contactEmail: "grants@illinois.gov",
      relationshipNotes: "Prior year awardee.",
      nextStep: "Compile final report and outcomes.",
      assignedOwner: "Grants Manager",
      documentsNeeded: "Final narrative, financials",
      submittedDate: "2025-09-12",
      decisionDate: "2025-11-01",
      awardAmount: 18000,
      declinedReason: "",
      renewalOpportunity: true,
      notes: "Report due to keep eligibility.",
    },
  ],
  donors: [
    {
      id: uid("donor", 1),
      name: "James & Patricia Holloway",
      organization: "Holloway Family",
      type: "Major Gift Prospect",
      givingCapacity: "$10,000+",
      interestArea: "Academic Programs",
      connection: "Board member referral",
      lastContact: "2026-05-12",
      nextStep: "Schedule lunch to discuss gift",
      askAmount: 10000,
      stage: "Cultivation",
      notes: "Interested in scholarship naming.",
    },
    {
      id: uid("donor", 2),
      name: "BMO Harris Bank",
      organization: "BMO Harris",
      type: "Corporate Sponsor",
      givingCapacity: "$15,000",
      interestArea: "Golf Invitational",
      connection: "Existing sponsor",
      lastContact: "2026-06-01",
      nextStep: "Send 2026 sponsorship packet",
      askAmount: 15000,
      stage: "Solicitation",
      notes: "Champion sponsor last year.",
    },
    {
      id: uid("donor", 3),
      name: "Coach Reggie Daniels",
      organization: "Chicago Public League",
      type: "Sports Leader",
      givingCapacity: "$1,000",
      interestArea: "Mentorship",
      connection: "Program volunteer",
      lastContact: "2026-04-20",
      nextStep: "Invite to fall showcase",
      askAmount: 1000,
      stage: "Stewardship",
      notes: "",
    },
    {
      id: uid("donor", 4),
      name: "Dr. Angela Foster",
      organization: "Foster Wellness Group",
      type: "Individual Donor",
      givingCapacity: "$2,500",
      interestArea: "Wellness",
      connection: "Former athlete parent",
      lastContact: "2026-05-30",
      nextStep: "Send year-end appeal",
      askAmount: 2500,
      stage: "Cultivation",
      notes: "",
    },
    {
      id: uid("donor", 5),
      name: "Marcus Tran",
      organization: "Self",
      type: "Former Athlete",
      givingCapacity: "$500",
      interestArea: "Career Exposure",
      connection: "Program alum (2014)",
      lastContact: "2026-03-15",
      nextStep: "Recruit as young professional ambassador",
      askAmount: 500,
      stage: "Qualification",
      notes: "Now works in tech; great speaker.",
    },
    {
      id: uid("donor", 6),
      name: "Liz Karbowski",
      organization: "SMART Sports Board",
      type: "Board Contact",
      givingCapacity: "$5,000",
      interestArea: "General Operating",
      connection: "Board Treasurer",
      lastContact: "2026-06-05",
      nextStep: "Confirm board give for FY26",
      askAmount: 5000,
      stage: "Solicitation",
      notes: "",
    },
    {
      id: uid("donor", 7),
      name: "Grossman Family Foundation",
      organization: "Grossman Family Foundation",
      type: "Foundation Contact",
      givingCapacity: "$20,000",
      interestArea: "STEM",
      connection: "Networking event",
      lastContact: "2026-05-18",
      nextStep: "Submit LOI",
      askAmount: 20000,
      stage: "Identification",
      notes: "",
    },
  ],
  golfSponsors: [
    { id: uid("gs", 1), name: "BMO Harris", level: "Champion Sponsor", amount: 15000, confirmed: true, followUp: "Send logo request" },
    { id: uid("gs", 2), name: "Wintrust", level: "Leadership Sponsor", amount: 10000, confirmed: true, followUp: "" },
    { id: uid("gs", 3), name: "Local Auto Group", level: "Foursome Sponsor", amount: 5000, confirmed: false, followUp: "Awaiting signed agreement" },
    { id: uid("gs", 4), name: "Riverside Dental", level: "Hole Sponsor", amount: 1000, confirmed: true, followUp: "" },
  ],
  golfFoursomes: [
    { id: uid("gf", 1), captain: "Tom Becker", organization: "Becker Realty", players: 4, amount: 2000, paid: true },
    { id: uid("gf", 2), captain: "Sandra Liu", organization: "Liu CPA", players: 4, amount: 2000, paid: false },
  ],
  golfPlayers: [
    { id: uid("gp", 1), name: "David Ortiz", organization: "Self", amount: 500, paid: true },
    { id: uid("gp", 2), name: "Karen Webb", organization: "Webb Designs", amount: 500, paid: false },
  ],
  golfAuction: [
    { id: uid("ga", 1), item: "Cubs Suite Experience", donor: "Anonymous", estimatedValue: 3000, type: "Auction" },
    { id: uid("ga", 2), item: "Signed Bulls Jersey", donor: "Sports Leader Network", estimatedValue: 800, type: "Auction" },
    { id: uid("ga", 3), item: "Catering for Event", donor: "Taste of Chicago Catering", estimatedValue: 4500, type: "In-kind" },
    { id: uid("ga", 4), item: "Golf Cart Sponsorship", donor: "Harborside", estimatedValue: 2500, type: "In-kind" },
  ],
  golfExpenses: [
    { id: uid("ge", 1), item: "Course & Greens Fees", amount: 12000, category: "Venue" },
    { id: uid("ge", 2), item: "Catering (cash portion)", amount: 4000, category: "Food & Beverage" },
    { id: uid("ge", 3), item: "Printing & Signage", amount: 1500, category: "Marketing" },
    { id: uid("ge", 4), item: "Prizes & Awards", amount: 1200, category: "Program" },
  ],
  board: [
    { id: uid("bm", 1), name: "Liz Karbowski", giveGoal: 5000, given: 5000, introductions: 3, meetingsScheduled: 2, prospectsAssigned: 4, sponsorOutreach: 3 },
    { id: uid("bm", 2), name: "Andre Phillips", giveGoal: 5000, given: 2500, introductions: 2, meetingsScheduled: 1, prospectsAssigned: 3, sponsorOutreach: 1 },
    { id: uid("bm", 3), name: "Maria Gonzalez", giveGoal: 5000, given: 5000, introductions: 4, meetingsScheduled: 3, prospectsAssigned: 5, sponsorOutreach: 2 },
    { id: uid("bm", 4), name: "Kevin Wu", giveGoal: 5000, given: 1000, introductions: 1, meetingsScheduled: 0, prospectsAssigned: 2, sponsorOutreach: 0 },
    { id: uid("bm", 5), name: "Denise Carter", giveGoal: 5000, given: 3000, introductions: 2, meetingsScheduled: 2, prospectsAssigned: 3, sponsorOutreach: 2 },
  ],
};