/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as GolfRouteImport } from './routes/golf'
import { Route as DonorsRouteImport } from './routes/donors'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfRoute = GolfRouteImport.update({
  id: '/golf',
  path: '/golf',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorsRoute = DonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/donors': typeof DonorsRoute
  '/golf': typeof GolfRoute
  '/grants': typeof GrantsRoute
  '/programs': typeof ProgramsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/donors': typeof DonorsRoute
  '/golf': typeof GolfRoute
  '/grants': typeof GrantsRoute
  '/programs': typeof ProgramsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/donors': typeof DonorsRoute
  '/golf': typeof GolfRoute
  '/grants': typeof GrantsRoute
  '/programs': typeof ProgramsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board' | '/donors' | '/golf' | '/grants' | '/programs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board' | '/donors' | '/golf' | '/grants' | '/programs'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/donors'
    | '/golf'
    | '/grants'
    | '/programs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  DonorsRoute: typeof DonorsRoute
  GolfRoute: typeof GolfRoute
  GrantsRoute: typeof GrantsRoute
  ProgramsRoute: typeof ProgramsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf': {
      id: '/golf'
      path: '/golf'
      fullPath: '/golf'
      preLoaderRoute: typeof GolfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donors': {
      id: '/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof DonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  DonorsRoute: DonorsRoute,
  GolfRoute: GolfRoute,
  GrantsRoute: GrantsRoute,
  ProgramsRoute: ProgramsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
